ctitle: Sashidhar Bezawada
logo: /images/Image1.jpg
description:
  <p align="left">
  Data Engineer and DataScience Graduate 
  <br><br>
  <em>Highly-skilled Data Enigneer with 19 years of experience in developing, implementation and optimization of data plumbing systems and ETL processes. Led multiple teams of  developers to implement data-driven solutions. Collaborated with data scientists and engineers to develop data pipelines. With strong business understanding and knowledge in Financial domain.</em>
  <br><br>
  </p>
theme: jekyll-theme-Cayman
